[models]
name = ["fm", "deepfm"]

[work]
models = "/tmp/models"
tmp = "/tmp/tfs"
zip_dir = "model.tf"

[envs]
ak = "S3_ACCESS_KEY_ID"
sk = "S3_SECRET_ACCESS_KEY"
bucket = "S3_BUCKET"
region = "S3_REGION"
key_template = "S3_KEY_TEMPLATE"

[daemon]
interval = 600